### ISSUE TITLE
Python 3 port

### ISSUE THREAD

**Issue by arkadi-kagan** [naught101/sobol_seq#1]
Hi,
Would it be possible to submit Python 3 port?

In my Python 3.4 I do the follow changes:
(I am referring to what-ever version is coming with "pip install sobol" - reports 0.9)
1. Update imports in `__init__.py`
   `from sobol.sobol_seq import i4_uniform, i4_sobol  # noqa`
   instead of
   `from sobol_seq import i4_uniform, i4_sobol  # noqa`
2. Update print function to Python 3 standard
   It works in Python 2x anyway.
   `print('x')`
   instead of
   `print 'x'`
3. Missing xrange in Python 3
   Because xrange is more effective in Python 2x, you shouldn't replace it with range blindly:

```
try:
    xrange
except NameError:
    xrange = range
```

For me that's all.
I didn't do thorough testing through, something may be still missing.

Thanks,
Arkadi.

**Comment by naught101** [comment]
Hrm.. that pypi version is from crankycoder's fork. They never discussed putting this on pypi with me. The version in this repository is already python 3 compatible (and doesn't have the xrange hack, because 1. it's a hack, and 2. it's really time people started moving away from python 2.x). 

You can either use the version in this repository via git or via conda/binstar (which I'd recommend over pip anyway), or you can post a request to crankycoder's fork's issue queue.

**Comment by naught101** [comment]
binstar version available at https://binstar.org/naught101/sobol_seq, btw.

**Comment by arkadi-kagan** [comment]
Thanks.
