### ISSUE TITLE
pypi sobol_seq package is out of date

### ISSUE THREAD

**Issue by orso82** [naught101/sobol_seq#18]
I just installed `sobol_seq` with pip
```
>> pip install sobol_seq
Collecting sobol_seq
  Downloading https://files.pythonhosted.org/packages/89/7a/7b374fd1f100bfea2624190f3dd879029e1aabe70d34e279ef456d522717/sobol_seq-0.1.2.zip
Installing collected packages: sobol-seq
  Running setup.py install for sobol-seq ... done
Successfully installed sobol-seq-0.1.2
```
and this version does not have the `i4_sobol_generate_std_normal` function

**Comment by Chin-I** [comment]
Same here!
But stiil appreciate this python version.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-18-c7856f6cecd6> in <module>()
----> 1 sobol_seq.i4_sobol_generate_std_normal(2,2)

AttributeError: module 'sobol_seq' has no attribute 'i4_sobol_generate_std_normal'

**Comment by michaelosthege** [comment]
Unfortunately the out-of-date PyPI version makes it very unconvenient to use `sobol_seq` as a dependency.

@naught101 Could I help you to update the PyPI release? For me that would be a lot nicer than depending on a GitHub repository that could change at any time..
(I can't use the current release, because of #14)

**Comment by naught101** [comment]
#14 is not fixed, because I haven't had time to. Feel free to send a pull request, and I'll merge it as quickly as I can (ideally with tests, but I haven't had time for that either :roll_eyes: )

Once #14 is fixed, it would make sense to bump the release version in setup.py, and then anyone can push a new version to pypi.

**Comment by naught101** [comment]
@michaelosthege thanks for the fix in #19. Do you want to push a new package to pypi? instructions at https://packaging.python.org/tutorials/packaging-projects/

Also, if you are actively using the package, and you're interested, I'm happy to add you as a maintainer here.

**Comment by michaelosthege** [comment]
Instead of pushing yet another alternative package, I'd rather like to get the existing ones updated.

It looks like you, @naught101 pushed to https://conda.binstar.org/naught101 while @CnrLwlss did the PyPI upload to https://pypi.org/project/sobol_seq/

If you add me as a maintainer, I can tag a release on GitHub. I'll familiarize myself with PyPI/conda to see how we can get both release updated.

**Comment by naught101** [comment]
I invited you, and added 2 releases (v0.1.2 and v0.2.0). I'm pretty sure anyone can push stuff to pypi. As long as it has the same package name it will just update to the newest version.

**Comment by michaelosthege** [comment]
Thanks. Not anybody can update a package - that would be a major security issue. But it should be possible to add multiple maintainers.

The tags on Github are a good thing too. They can be used to pin a specific version via `requirements. txt`. I'll instructions for that to the Readme.

**Comment by naught101** [comment]
Fixed on pypi now
